Request incremental hot copy if journal hot copy is temporary disabled (#262)
NuoDB 4.3+ will temporary suspend the journal hot copy during archive sync.
When coordinated hot copy operation is performed, the error is shown either in
the "message" attribute of the hot copy response or when the hot copy is
initiated depending on the choice of the coordinator SM

For example:
- "message": "Hot copy failed: Node 6: Journal hot copy has been suspended due
  to archive sync. Full or incremental hot copy must be completed before
 journal hot copy."
- 'backup database' failed: Failure while performing hot-copy: Error while
  sending engine request: Journal hot copy has been suspended due to archive
  sync. Full or incremental hot copy must be completed before journal hot copy.

If full or incremental hot copy is already requested, the error message will be
different: "Journal hot copy has been suspended due to archive sync. The
running incremental hot copy must complete before journal hot copy can start."

A new incremental hot copy is requested now if the journal hot copy fails
because it is temporary disabled.

diff --git a/stable/database/files/nuobackup b/stable/database/files/nuobackup
--- a/stable/database/files/nuobackup
+++ b/stable/database/files/nuobackup
@@ -46,6 +46,7 @@ labels=""
 semaphore=""
 timeout=""
 backup_root=$BACKUP_DIR
+retry_failed="True"
 
 function get_current_backup() {
    output=$( nuodocker get current-backup \
@@ -68,14 +69,15 @@ function execute_backup() {
 
    # call nuodocker to perform the actual backup
    echo "Starting ${type} backup for database ${db_name} on processes with labels '${labels}' ..."
-   nuodocker backup database \
+   output=$(nuodocker backup database \
       --db-name "${db_name}" \
       --type "${type}" \
       --backup-root "${backup_root}" \
       --labels "${labels}" \
-      "${extra_flags[@]}"
+      "${extra_flags[@]}" 2>&1)
 
    retval=$?
+   echo "$output"
    if [ $retval != 0 ]; then
       echo >&2 "Error running hotcopy $retval"
       # Store failed backupset in KV store
@@ -87,8 +89,19 @@ function execute_backup() {
                --key "$NUODB_BACKUP_KEY/$db_name/${backup_group}/failed" \
                --value "${failed} ${backupset}" --expected-value "${failed}"
          fi
-      fi 
-      exit $retval
+      fi
+      if [ -n "$retry_failed" ] && [ "$type" = "journal" ] && echo "$output" | grep -q "Full or incremental hot copy must be completed before journal hot copy"; then
+         # journal hot copy has been temporarly suspended due to archive sync;
+         # perform incremental first and once completed retry the journal hot
+         # copy
+         retry_failed=""
+         echo "Executing incremental hot copy as journal hot copy is temporarily suspended"
+         execute_backup "incremental" || return $?
+         # retry the journal backup which should succeed now
+         execute_backup "journal"
+         retval=$?
+      fi
+      return $retval
    fi
 
    if [ "$type" = "full" ] && [ -n "$backup_group" ]; then
