Change tabs to spaces; skip build

diff --git a/stable/database/files/nuobackup b/stable/database/files/nuobackup
--- a/stable/database/files/nuobackup
+++ b/stable/database/files/nuobackup
@@ -48,59 +48,59 @@ wait_for_num_processes=0
 wait_timeout=300
 
 function await() {
-	local timeout=$1
-	shift
-	local end_time=$(( $(date -u +%s) + $timeout ))
-	local rc=0
-	while [ "$(date -u +%s)" -lt "$end_time" ]; do
-		eval "$*"
-		rc=$?
-		if [ $rc -eq 0 ]; then
-			return $rc
-		fi
-		sleep 1
-	done
-	return 124
+   local timeout=$1
+   shift
+   local end_time=$(( $(date -u +%s) + $timeout ))
+   local rc=0
+   while [ "$(date -u +%s)" -lt "$end_time" ]; do
+      eval "$*"
+      rc=$?
+      if [ $rc -eq 0 ]; then
+         return $rc
+      fi
+      sleep 1
+   done
+   return 124
 }
 
 function check_backup_processes() {
-	declare -a label_patterns=()
+   declare -a label_patterns=()
    local all_process_labels=""
 
-	for ((i=0; i<${#labels_arr[@]}; i+=2)); do
-	  label_patterns[${#label_patterns[@]}]="\"${labels_arr[i]}\"\s*:\s*\"${labels_arr[i+1]}\""
-	done
+   for ((i=0; i<${#labels_arr[@]}; i+=2)); do
+     label_patterns[${#label_patterns[@]}]="\"${labels_arr[i]}\"\s*:\s*\"${labels_arr[i+1]}\""
+   done
 
    all_process_labels="$(nuocmd --api-server $NUOCMD_API_SERVER show database \
       --db-name $db_name \
       --process-format '#{engine_type} {state} {labels}')" || return $?
 
-	num_processes=0
-	while read process_labels; do
+   num_processes=0
+   while read process_labels; do
       [ -z "$process_labels" ] && continue
-		parsed_labels=$(echo "$process_labels" | tr "'" '"' | python -m json.tool 2>&1)
-		if [ $? -ne 0 ];then
-			echo "Unable to parse SM process labels ${process_labels}: ${parsed_labels}" 2>&1
-			continue
-		fi
-		match=true
-		for pattern in ${label_patterns[@]}; do
-			if ! echo "${parsed_labels}" | grep -E -q "${pattern}"; then
-				# Some of the labels are not found
-				match=""
-				break
-			fi
-		done
-		if [ -n "$match" ]; then
-			num_processes=$(( num_processes+1 ))
-		fi
-	done <<< "$( echo "$all_process_labels" | sed -n -e 's/\s*#SM RUNNING //p')"
+      parsed_labels=$(echo "$process_labels" | tr "'" '"' | python -m json.tool 2>&1)
+      if [ $? -ne 0 ];then
+         echo "Unable to parse SM process labels ${process_labels}: ${parsed_labels}" 2>&1
+         continue
+      fi
+      match=true
+      for pattern in ${label_patterns[@]}; do
+         if ! echo "${parsed_labels}" | grep -E -q "${pattern}"; then
+            # Some of the labels are not found
+            match=""
+            break
+         fi
+      done
+      if [ -n "$match" ]; then
+         num_processes=$(( num_processes+1 ))
+      fi
+   done <<< "$( echo "$all_process_labels" | sed -n -e 's/\s*#SM RUNNING //p')"
 
-	if [ "$num_processes" -eq "$wait_for_num_processes" ]; then
-		return 0
-	else
-		return 1
-	fi
+   if [ "$num_processes" -eq "$wait_for_num_processes" ]; then
+      return 0
+   else
+      return 1
+   fi
 }
 
 while [ $# -gt 0 ];
