Don't swallow the error message

diff --git a/stable/database/files/nuobackup b/stable/database/files/nuobackup
--- a/stable/database/files/nuobackup
+++ b/stable/database/files/nuobackup
@@ -79,6 +79,7 @@ function execute_backup() {
    retval=$?
    echo "$output"
    if [ $retval != 0 ]; then
+      echo >&2 "Error running hotcopy $retval"
       # Store failed backupset in KV store
       if [ "$type" = "full" ] && [ -n "$backup_group" ]; then
          backupset=$(get_current_backup)
@@ -89,18 +90,14 @@ function execute_backup() {
                --value "${failed} ${backupset}" --expected-value "${failed}"
          fi
       fi
-      if [ -n "$retry_failed" ]; then
+      if [ -n "$retry_failed" ] && [ "$type" = "journal" ] && echo "$output" | grep -q "Full or incremental hot copy must be completed before journal hot copy"; then
          # Retry only once if failures can be automatically resolved
          retry_failed=""
-         if [ "$type" = "journal" ] && echo "$output" | grep -q "Full or incremental hot copy must be completed before journal hot copy"; then
-            echo "Executing incremental hot copy as journal hot copy is temporarily suspended"
-            execute_backup "incremental" || return $?
-            # retry the journal backup which should succeed now
-            execute_backup "journal"
-            retval=$?
-         fi
-      else
-         echo >&2 "Error running hotcopy ${retval}: ${output}"
+         echo "Executing incremental hot copy as journal hot copy is temporarily suspended"
+         execute_backup "incremental" || return $?
+         # retry the journal backup which should succeed now
+         execute_backup "journal"
+         retval=$?
       fi
       return $retval
    fi
