Add diagnostics of AP address/DNS resolution

diff --git a/stable/database/files/nuosm b/stable/database/files/nuosm
--- a/stable/database/files/nuosm
+++ b/stable/database/files/nuosm
@@ -21,6 +21,12 @@ DB_DIR=${NUODB_ARCHIVEDIR}/${NUODB_DOMAIN}/${DB_NAME}
 NUODB_BINDIR=$NUODB_HOME/bin
 [ -z "$NUOCMD" ] && NUOCMD="$NUODB_BINDIR/nuocmd --api-server $NUOCMD_API_SERVER"
 
+# see which APs are accessible
+for i in {0..2}; do
+  ping -c 1 admin-${NAMESPACE}-test-$i.${NAMESPACE}
+  [ "$?" = "0" ] && echo "FOUND AP-$i" || echo "FAILED to find AP-$i"
+done
+
 # attempt to retain the previous crash directory (within the configured window to avoid filling the disk)
 crashcount=$(find $NUODB_CRASHDIR/core* -maxdepth 0 ! -type d 2>/dev/null | wc -l)
 if [ $crashcount -ge 1 ]; then
