Remove nuosm exit codes

diff --git a/stable/database/files/nuosm b/stable/database/files/nuosm
--- a/stable/database/files/nuosm
+++ b/stable/database/files/nuosm
@@ -14,12 +14,6 @@
 
 : ${NUODB_IMPORT_CREDENTIALS:=:}
 
-ERR_ADMIN_UNAVAILABLE=71
-ERR_BACKUPSET_NOT_FOUND=72
-ERR_NO_SPACE=73
-ERR_INCORRECT_BACKUP=74
-ERR_RESTORE_FAILED=75
-
 startup_key="/nuodb/nuosm/startup"
 first_req="$NUODB_RESTORE_REQUEST_PREFIX/$DB_NAME/first"
 restore_req="$NUODB_RESTORE_REQUEST_PREFIX/$DB_NAME/restore"
@@ -50,7 +44,7 @@ export DB_NAME NUODB_STORAGE_PASSWORDS_DIR
 # function - report an error and exit
 #
 function die() {
-  retval=$1
+  local retval=$1
   shift
   error="$@"
   [ -n "$wotIdid" ] && error="Error while ${wotIdid}: ${error}"
@@ -135,7 +129,7 @@ function resurrectRemovedArchive() {
 #
 function perform_restore() {
 
-  retval=0
+  local retval=0
   error=
 
   log "Restoring $restore_source; existing archive directores: $( ls -l $DB_PARENTDIR )"
@@ -169,9 +163,8 @@ function perform_restore() {
     archSpace="$(df --output=avail $DB_DIR | grep -o ' *[0-9]\+')"
     if [ $(( archSize + 1024000 > archSpace )) ]; then
       rm -rf $tarfile
-      retval=$ERR_NO_SPACE
       error="Insufficient space for restore after archive has been saved to TAR."
-      return $retval
+      return 1
     fi
 
     undo="tar xf $tarfile -C $DB_PARENTDIR"
@@ -249,8 +242,7 @@ function perform_restore() {
   if [ -n "$restoredName" -a "$restoredName" != "$DB_NAME" ]; then
     $undo
     error="Restore: incorrect backup specified. Database name is $DB_NAME but archive is for $restoredName"
-    retval=$ERR_INCORRECT_BACKUP
-    return $retval
+    return 1
   fi
 
   # completely delete my previous archive metadata
@@ -262,6 +254,8 @@ function perform_restore() {
   fi
 
   [ -n "$NUODB_DEBUG" ] && ls -l $DB_DIR
+
+  return 0
 }
 
 #=============================
@@ -284,7 +278,7 @@ fi
 trace "checking Admin layer"
 status="$(nuocmd check servers --check-leader --timeout 30 2>&1)"
 retval=$?
-[ $retval -ne 0 ] && die $ERR_ADMIN_UNAVAILABLE "(nuosm) Admin layer is inoperative - exiting: $status"
+[ $retval -ne 0 ] && die 1 "(nuosm) Admin layer is inoperative - exiting: $status"
 
 trace "checking archive raft metadata"
 myArchive=$( nuocmd show archives --db-name $DB_NAME --archive-format "archive-id: {id}" | sed -En "/^archive-id: / {N; /$HOSTNAME/ s/^archive-id: ([0-9]+).*$/\1/; T; p}" | head -n 1 )
@@ -416,7 +410,7 @@ if [ -n "$restore_requested" -a -n "$restore_source" ]; then
     wotIdid=""
     if ! isRestoreSourceAvailable "$restore_source"; then
       error="Backupset $restore_source cannot be found in $NUODB_BACKUPDIR"
-      die $ERR_BACKUPSET_NOT_FOUND $error
+      die 1 $error
     fi
 
     # KAA will remove archives for scaled down SM statefulsets; 
@@ -434,12 +428,9 @@ if [ -n "$restore_requested" -a -n "$restore_source" ]; then
 
     # and restore the data
     trace "performing restore"
-    perform_restore
+    perform_restore || die $? "$error"
 
     wotIdid=""
-
-    # any error is a fatal error
-    [ $retval -ne 0 ] && die $retval $error
 
     log "Restored from $restore_source"
 
@@ -458,7 +449,7 @@ if [ -n "$restore_requested" -a -n "$restore_source" ]; then
   retry=0
   until owner=$( nuocmd get value --key $startup_key/$DB_NAME ); [ "$owner" = "$HOSTNAME" -o "$NUODB_SEQUENCE_SYNC" = "false" ] ; do
 
-    [ "$owner" = "" -a $retry -gt 0 ] && die $ERR_RESTORE_FAILED "Fatal error in database RESTORE - initial SM has exited with error - $HOSTNAME aborting also"
+    [ "$owner" = "" -a $retry -gt 0 ] && die 1 "Fatal error in database RESTORE - initial SM has exited with error - $HOSTNAME aborting also"
 
     # find the start-id of the SM that owns the semaphore
     owner_id=$( nuocmd show database --db-name $DB_NAME --skip-exited --process-format "{engine_type}: {address} start-id: {start_id};" | grep -E "^ *SM: $owner" | grep -Eo "start-id: [[0-9]+" | grep -Eo "[0-9]+")
@@ -489,12 +480,9 @@ if [ -n "$restore_requested" -a -n "$restore_source" ]; then
     trace "attempting to restore same backup as master SM to secondary SM"
 
     if isRestoreSourceAvailable "$restore_source"; then
-      perform_restore
-
-      log "Restored secondary archive to match primary restore"
-
       # any error in a SEED restore is a fatal error
-      [ $retval -ne 0 ] && die $retval $error
+      perform_restore || die $? "$error"
+      log "Restored secondary archive to match primary restore"
     fi
   fi
 
@@ -511,10 +499,8 @@ if [ -n "$restore_source" -a -z "$restore_requested" -a $atomCount -lt 20 -a $ca
   if isRestoreSourceAvailable "$restore_source"; then
     trace "restoring empty/damaged archive"
     log "Existing archive is empty or damaged - restoring and clearing metadata"
-    perform_restore
-  
     # any error in a IMPORT restore is a fatal error
-    [ $retval -ne 0 ] && die $retval $error
+    perform_restore || die $? "$error"
   else
       if [ "$myArchive" -ne "-1" ]; then
         # delete damaged archive metadata as new one will be created by nuodocker
